### ISSUE TITLE
nix-build -A package on node2nix generated code fails due to missing git

### ISSUE THREAD

**Issue by fadenb** [svanderburg/node2nix#38]
Hi,

**Issue:**
nix-build -A package fails while calling npm with error ENOGIT:
```
olm@1.0.0 /nix/store/578y89wckhxmqzl3q2pvmr4rq4vxsvqx-node-matrix-appservice-slack-0.1.0/lib/node_modules/matrix-appservice-slack/node_modules/matrix-js-sdk/node_modules/olm
randomstring@1.1.5 /nix/store/578y89wckhxmqzl3q2pvmr4rq4vxsvqx-node-matrix-appservice-slack-0.1.0/lib/node_modules/matrix-appservice-slack/node_modules/randomstring
array-uniq@1.0.2 /nix/store/578y89wckhxmqzl3q2pvmr4rq4vxsvqx-node-matrix-appservice-slack-0.1.0/lib/node_modules/matrix-appservice-slack/node_modules/randomstring/node_modules/array-uniq
npm ERR! git clone --template=/tmp/nix-build-node-matrix-appservice-slack-0.1.0.drv-0/.npm/_git-remotes/_templates --mirror git@github.com:matrix-org/matrix-appservice-bridge.git /tmp/nix-build-node-matrix-appservice-slack-0.1.0.drv-0/.npm/_git-remotes/git-github-com-matrix-org-matrix-appservice-bridge-git-ca40ff5-fbbf018a: undefined
npm ERR! git clone --template=/tmp/nix-build-node-matrix-appservice-slack-0.1.0.drv-0/.npm/_git-remotes/_templates --mirror git@github.com:matrix-org/matrix-appservice-bridge.git /tmp/nix-build-node-matrix-appservice-slack-0.1.0.drv-0/.npm/_git-remotes/git-github-com-matrix-org-matrix-appservice-bridge-git-ca40ff5-fbbf018a: undefined
npm ERR! Linux 4.9.9
npm ERR! argv "/nix/store/wf4wgj5y5nymcj2q8g48c2w4dzbzsv75-nodejs-6.9.1/bin/node" "/nix/store/wf4wgj5y5nymcj2q8g48c2w4dzbzsv75-nodejs-6.9.1/bin/npm" "--registry" "http://www.example.com" "--nodedir=/nix/store/vmgwl94wi8370gbwfxv4mnc45c4d4l0x-node-sources" "--production" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /nix/store/578y89wckhxmqzl3q2pvmr4rq4vxsvqx-node-matrix-appservice-slack-0.1.0/lib/node_modules/matrix-appservice-slack/npm-debug.log
builder for ‘/nix/store/cbvizmp4g6i6hfa94ir8iadbdisrn46y-node-matrix-appservice-slack-0.1.0.drv’ failed with exit code 1
error: build of ‘/nix/store/cbvizmp4g6i6hfa94ir8iadbdisrn46y-node-matrix-appservice-slack-0.1.0.drv’ failed
```

**How to reproduce:**
* Clone https://github.com/matrix-org/matrix-appservice-slack
* run node2nix to generate nix expressions
* run `nix-build -A package`
* Error

**Workaround**
For one package I was able to generate the nix expressions with node2nix and then remove all references to git in the package.json before running nix-build. This resulted in executable code but feels rather hacky ;)

**Comment by svanderburg** [comment]
This problem is related to issue #26 

I have just pushed a new commit that might be a solution that solves this issue. See #26 for more information.

**Comment by fadenb** [comment]
Thx, can confirm that this fixed the issues I had :)

**Comment by Ralith** [comment]
This issue occurs when passing `-6`, or when manually passing node 6 to default.nix, even when using latest master.

**Comment by jammerful** [comment]
I'm still seeing this issue while running against nodejs v7:

```
mime@1.3.6 /nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxx-0.0.39/lib/node_modules/mime
npm ERR! git clone --template=/nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/mapbox-gl-shaders.git /nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-shaders-git-de2ab007455aa2587c552694c68583f94c9f2747-ea1e5adb: undefined
npm ERR! git clone --template=/nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/mapbox-gl-shaders.git /nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-shaders-git-de2ab007455aa2587c552694c68583f94c9f2747-ea1e5adb: undefined
npm ERR! git clone --template=/nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/mapbox-gl-style-spec.git /nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-style-spec-git-83b1a3e5837d785af582efd5ed1a212f2df6a4ae-ff430f99: undefined
npm ERR! git clone --template=/nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/_templates --mirror git@github.com:mapbox/mapbox-gl-style-spec.git /nix/store/27amxamjavz3x9a35ydj5npm4bzmgpy0-node-dependencies-xxxxxx-0.0.39/lib/.npm/_git-remotes/git-github-com-mapbox-mapbox-gl-style-spec-git-83b1a3e5837d785af582efd5ed1a212f2df6a4ae-ff430f99: undefined
npm ERR! Linux 4.4.0-1039-aws
npm ERR! argv "/nix/store/bb469w79w3alpxd9ixz0xfr29mgn9d9l-nodejs-7.10.1/bin/node" "/nix/store/bb469w79w3alpxd9ixz0xfr29mgn9d9l-nodejs-7.10.1/bin/npm" "--registry" "http://www.example.com" "--nodedir=/nix/store/fwq5zfxccmm4fzcdna1g5jfi1xk1ya07-node-sources" "--production" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
```

**Comment by ldub** [comment]
This issue still occurs with the latest master. 

```
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://github.com/debris/bignumber.js.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.
```

**Comment by svanderburg** [comment]
@ldub Which package are you trying to deploy? Is it the same as the topic starter: 'matrix-appservice-slack' ?

**Comment by ldub** [comment]
No, its not. I apologize if I should've created a new issue for this. Here's the full repro of this bug on my machine, including nix info, node2nix info, and entire nix-build log: https://gist.github.com/ldub/282f7673b7fb77acce96b1c4623311a1

Thanks a lot for looking at this and please let me know how I can be of any help.

**Comment by svanderburg** [comment]
Closing this, since this problem is a new issue.
